// src/service-worker.js

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

// Precache files generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);

// Cache API responses or static assets
registerRoute(
  ({ request }) => request.destination === 'script' ||
                   request.destination === 'style' ||
                   request.destination === 'document',
  new StaleWhileRevalidate()
);
